Make ancient DNA damage correction optional
nf-core/mag pull request #459
Opened 2023-06-16 16:21 UTC by jfy133

This makes the damage correction subworkflow optional, i.e. ytou can run just pyDamage, and optionally turn on damage correction using freebayes and bcftools.

@alexhbnr please can you test, and let me know if you would refer to have it opt in (rather than opt out).

Also note this _does not yet_ include the hotfix in the patch for #449 , I will add that later as it requires more thinking due to the more complex inputs to bin refinement since domain classification has come in.

fixes #456

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mag/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/mag _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-06-21 06:22 UTC, alexhbnr requested changes
The skipping of the contig correction itself works well. However, when activating `--skip_ancient_damagecorrection` pyDamage doesn't export the files into a sample specific sub-folder any longer. The usual way was that pyDamage has sample-specific sub-folders in `Ancient_DNA/pydamage/analyze` and `Ancient_DNA/pydamage/filter`. At the moment, for every sample the same file is used and the results of the previous run sample are overwritten.

2023-06-21 06:54 UTC, jfy133 commented on conf/modules.config
> +            path: {"${params.outdir}/Ancient_DNA/pydamage/analyze/"${meta.assembler}-${meta.id}" },
```suggestion
            path: {"${params.outdir}/Ancient_DNA/pydamage/analyze/${meta.assembler}-${meta.id}" },
```

2023-06-21 06:54 UTC, jfy133 commented on conf/modules.config
> +            path: {"${params.outdir}/Ancient_DNA/pydamage/filter/"${meta.assembler}-${meta.id}" },
```suggestion
            path: {"${params.outdir}/Ancient_DNA/pydamage/filter/${meta.assembler}-${meta.id}" },
```

2023-06-21 08:06 UTC, jfy133 commented
Fix applied, waiting from results on tests as discussed on slack.

2023-06-22 06:41 UTC, alexhbnr approved these changes

2023-06-22 07:07 UTC, merged