Fix input to single-end MEGAHIT runs
nf-core/mag pull request #729
Opened 2024-12-10 11:59 UTC by jfy133

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mag/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/mag _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core pipelines lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-12-10 11:59 UTC, jfy133 commented on CHANGELOG.md
> +- [#727](https://github.com/nf-core/mag/pull/727) - Fixed misspecified multi-FASTQ input for single-end data in MEGAHIT (reported by John Richards, fix by @jfy133)
```suggestion
- [#729](https://github.com/nf-core/mag/pull/729) - Fixed misspecified multi-FASTQ input for single-end data in MEGAHIT (reported by John Richards, fix by @jfy133)
```

2024-12-10 12:00 UTC, jfy133 commented
Closes https://github.com/nf-core/mag/issues/727

2024-12-10 12:33 UTC, sateeshperi approved these changes

2024-12-10 13:35 UTC, sateeshperi requested changes
fix tests

2024-12-11 09:32 UTC, jfy133 commented
Uh-oh....

2024-12-11 19:15 UTC, jfy133 commented
Replicated failure and this is the error:

```
(nf-core) james@bionb103:~/git/nf-core/mag/testing/work/17/c9f0a089e501713e8d3ba4fd0b5846 (fix-megahit)$ cat MEGAHIT-MetaBAT2-test_minigut.1.fa_busco.err
2024-12-11 17:04:42 ERROR:      list_of_reference_markers.bacteria_odb10.txt is not a valid option for 'placement_files'
2024-12-11 17:04:42 ERROR:      BUSCO analysis failed!
2024-12-11 17:04:42 ERROR:      Check the logs, read the user guide (https://busco.ezlab.org/busco_userguide.html), and check the BUSCO issue board on https://gitlab.com/ezlab/busco/issues

```

2024-12-14 02:54 UTC, sateeshperi approved these changes

2024-12-14 02:55 UTC, merged