Migrate to nf-core BUSCO module (WIP)
nf-core/mag pull request #730
Opened 2024-12-12 05:14 UTC by dialvarezs

This PR migrates from the local BUSCO module to the nf-core one.

TODO:
[ ] Handle all database posibilites (`.tar.gz` archive, busco download path, none)
[ ] Handle `busco_save_download`
[ ] Add new `--busco_lineage` param
[ ] Deprecate ` --busco_auto_lineage_prok`

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mag/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/mag _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core pipelines lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-12-13 13:22 UTC, prototaxites commented
> How should I deprecate a param (busco_clean)?

Is there scope to add this as an optional input to the BUSCO module itself? For some context, the problem I encountered with BUSCO was that the temporary working files take up a lot of storage space on disk, so running BUSCO on (in my case) 1000s of bins meant that my available scratch quota was quickly filling up and leading to mag runs that couldn't finish. So it would be good to try and keep this as an option if possible as I imagine this is a plausible issue for other mag users also!

2024-12-13 13:42 UTC, dialvarezs commented
Hi @prototaxites,
I don’t think there should be any issue with porting the "clean" part of the script to the nf-core module. I’ll go ahead and open a PR for it.
By the way, the temporary storage usage should be significantly reduced now, as it only runs one BUSCO instance per sample.

2024-12-13 14:57 UTC, dialvarezs commented
The tests I ran for this PR look like this:

auto
![image](https://github.com/user-attachments/assets/cb7916b0-9fc9-447b-b869-0728410361c1)

auto_prok
![image](https://github.com/user-attachments/assets/48af039e-2bd4-4804-9504-b0805dcb3d06)

How do these numbers look to you?
For 20 samples, I estimate we could trim ~150 GB in auto (and about half of that in auto_prok).

2025-01-02 07:30 UTC, dialvarezs commented
I made a last minor addition to this PR, I replaced the module used to combine bin qc summaries by a nf-core one.

2025-01-08 12:23 UTC, dialvarezs commented on conf/test.config
>      busco_clean                 = true
Sure, I will remove it

2025-01-19 16:30 UTC, jfy133 requested changes
Thank you for your patience @dialvarezs !

Some initial comments, however when comparing `-profile test` on your branch and current `dev`, I get the following results:

```
(nf-core) james@bionb103:~/git/nf-core/mag/testing (dev)$ cat results_dev/GenomeBinning/QC/busco_summary.tsv 
GenomeBin       Specific lineage dataset        %Complete (specific)    %Complete and single-copy (specific)    %Complete and duplicated (specific)     %Fragmented (specific)  %Missing (specific)        Total number (specific)
MEGAHIT-MetaBAT2-test_minigut_sample2.unbinned.2.fa     bacteria_odb10  0.0     0.0     0.0     0.0     100.0   124
SPAdes-MaxBin2-test_minigut_sample2.noclass.1.fa        bacteria_odb10  0.0     0.0     0.0     0.0     100.0   124
SPAdes-MetaBAT2-test_minigut.1.fa       bacteria_odb10  13.7    13.7    0.0     2.4     83.9    124
MEGAHIT-MetaBAT2-test_minigut.unbinned.2.fa     bacteria_odb10  0.0     0.0     0.0     0.8     99.2    124
MEGAHIT-MaxBin2-test_minigut.001.fa     bacteria_odb10  19.4    19.4    0.0     0.8     79.8    124
SPAdes-MetaBAT2-test_minigut.unbinned.2.fa      bacteria_odb10  0.0     0.0     0.0     0.0     100.0   124
MEGAHIT-MetaBAT2-test_minigut_sample2.unbinned.1.fa     bacteria_odb10  0.0     0.0     0.0     0.0     100.0   124
MEGAHIT-MetaBAT2-test_minigut.1.fa      bacteria_odb10  12.1    12.1    0.0     3.2     84.7    124
SPAdes-MetaBAT2-test_minigut_sample2.unbinned.1.fa      bacteria_odb10  0.0     0.0     0.0     0.0     100.0   124
SPAdes-MetaBAT2-test_minigut.2.fa       bacteria_odb10  20.2    20.2    0.0     1.6     78.2    124
SPAdes-MaxBin2-test_minigut_sample2.noclass.2.fa        bacteria_odb10  0.0     0.0     0.0     0.0     100.0   124
MEGAHIT-MetaBAT2-test_minigut.2.fa      bacteria_odb10  19.4    19.4    0.0     0.0     80.6    124
MEGAHIT-MetaBAT2-test_minigut.unbinned.1.fa     bacteria_odb10  0.0     0.0     0.0     0.0     100.0   124
MEGAHIT-MaxBin2-test_minigut.002.fa     bacteria_odb10  13.7    13.7    0.0     4.8     81.5    124
SPAdes-MetaBAT2-test_minigut_sample2.unbinned.2.fa      bacteria_odb10  0.0     0.0     0.0     0.0     100.0   124
SPAdes-MetaBAT2-test_minigut.unbinned.1.fa      bacteria_odb10  0.0     0.0     0.0     0.8     99.2    124
SPAdes-MaxBin2-test_minigut.001.fa      bacteria_odb10  20.2    20.2    0.0     1.6     78.2    124
SPAdes-MaxBin2-test_minigut_sample2.001.fa      bacteria_odb10  2.4     2.4     0.0     4.8     92.8    124
SPAdes-MaxBin2-test_minigut.002.fa      bacteria_odb10  13.7    13.7    0.0     3.2     83.1    124
(nf-core) james@bionb103:~/git/nf-core/mag/testing (dev)$ cat results_dialvarezs-busco/GenomeBinning/QC/BUSCO/test_minigut/test_minigut-bacteria_odb12-busco.batch_summary.txt 
Input_file      Dataset Complete        Single  Duplicated      Fragmented      Missing n_markers       Scaffold N50    Contigs N50     Percent gaps    Number of scaffolds
SPAdes-MetaBAT2-test_minigut.unbinned.2.fa      Run failed; check logs
SPAdes-MetaBAT2-test_minigut.unbinned.1.fa      Run failed; check logs
```

i.e, the runs on your BUSCO implementation are failing for some reason

We need to investigate if this is valid output or not given the new version of BUSCO and the database.

It would also be helpful if @skrakau (if she has time) could look at this to make sure we aren't removing anything important - I note that the custom `busco_run.sh` script of Sabrina's original module has A LOT more LoC than the new module has... (which maybe due to the new version of BUSCO) but I have 0 experience with BUSCO myself.

2025-01-19 16:30 UTC, jfy133 commented on subworkflows/local/gtdbtk.nf
> -                        def missing, duplicated
This deletion means that the pipeline is no longer backwards compatible with older versions of the database, correct? This is important to list in te changelog

2025-01-19 16:33 UTC, jfy133 commented
reason for failures I think:

```
********************************************************************************
Running BUSCO on file: /home/james/git/nf-core/mag/testing/work/24/90cfdc2ff2e2e1083f6c1f6e74b3ff/input_seqs/SPAdes-MetaBAT2-test_minigut.unbinned.2.fa
********************************************************************************


2025-01-19 15:55:58 INFO:busco.BuscoRunner      Input file is /home/james/git/nf-core/mag/testing/work/24/90cfdc2ff2e2e1083f6c1f6e74b3ff/input_seqs/SPAdes-MetaBAT2-test_minigut.unbinned.2.fa
2025-01-19 15:55:58 ERROR:busco.BuscoRunner     Unable to run BUSCO in offline mode. Dataset /home/james/git/nf-core/mag/testing/work/24/90cfdc2ff2e2e1083f6c1f6e74b3ff/busco_db/lineages/bacteria_odb12 does not exist.
2025-01-19 15:55:58 INFO:busco.BuscoRunner

********************************************************************************
Running BUSCO on file: /home/james/git/nf-core/mag/testing/work/24/90cfdc2ff2e2e1083f6c1f6e74b3ff/input_seqs/SPAdes-MetaBAT2-test_minigut.unbinned.1.fa
********************************************************************************


2025-01-19 15:55:58 INFO:busco.BuscoRunner      Input file is /home/james/git/nf-core/mag/testing/work/24/90cfdc2ff2e2e1083f6c1f6e74b3ff/input_seqs/SPAdes-MetaBAT2-test_minigut.unbinned.1.fa
2025-01-19 15:55:58 ERROR:busco.BuscoRunner     Unable to run BUSCO in offline mode. Dataset /home/james/git/nf-core/mag/testing/work/24/90cfdc2ff2e2e1083f6c1f6e74b3ff/busco_db/lineages/bacteria_odb12 does not exist.
2025-01-19 15:55:58 DEBUG:urllib3.connectionpool        Starting new HTTPS connection (1): busco-data.ezlab.org:443
2025-01-19 15:55:58 DEBUG:urllib3.connectionpool        Starting new HTTPS connection (1): busco-data.ezlab.org:443
2025-01-19 15:55:59 DEBUG:urllib3.connectionpool        https://busco-data.ezlab.org:443 "PUT /upload/rundata202501191555589915025.txt HTTP/11" 201 0
2025-01-19 15:55:59 DEBUG:urllib3.connectionpool        https://busco-data.ezlab.org:443 "PUT /upload/rundata202501191555589915025.txt HTTP/11" 201 0
2025-01-19 15:55:59 DEBUG:busco.run_BUSCO       File uploaded successfully.
```

2025-02-10 21:20 UTC, dialvarezs commented on subworkflows/local/bin_qc.nf
> +                BUSCO_UNTAR([[id: 'busco_db'], ch_busco_db])
I just realized that this is problematic because `ch_busco_db` is a file, not a channel. To avoid confusion, I’m considering removing the `ch_` prefix. Do you agree on that, or would it be better to refactor so it becomes a channel?

2025-03-03 01:12 UTC, dialvarezs commented on nextflow_schema.json
> -                "busco_clean": {
It's integrated now in this PR now.

2025-03-13 00:41 UTC, dialvarezs commented on conf/modules.config
> +                pattern: "busco_downloads/lineages/*",
Yes, it's the same structure that makes possible to run busco in offline mode with that directory.

2025-03-13 00:42 UTC, dialvarezs commented on modules/nf-core/checkm2/predict/main.nf
> +    tuple val(meta), path("${prefix}_checkm2_report.tsv"), emit: checkm2_tsv
Updated.

2025-03-13 00:43 UTC, dialvarezs commented on subworkflows/local/bin_qc.nf
> +        qc_summaries = BUSCO_BUSCO.out.batch_summary
Batch summaries are the same as before, but the structure changed a little bit. I updated `output.md` to the new structure.

2025-03-13 01:00 UTC, dialvarezs commented on subworkflows/local/gtdbtk.nf
> -                        def missing, duplicated
Yes, but it's BUSCO itself that doesn't support older versions of downloaded databases, as it now expects the new odb12 lineages (which is why you encountered that error).

Maybe it's better to add a notice in the release instead of the changelog?

2025-03-13 01:19 UTC, dialvarezs commented
Hi again @jfy133. I did more comprehensive testing, specially with offline mode and I realized that there were some problems, so I updated the BUSCO module again and made changes in the pipeline. So, when you're available, please review this new changes.

> I note that the custom busco_run.sh script of Sabrina's original module has A LOT more LoC than the new module has...

Yes, Sabrina's script included a lot of adjustments to simplify the BUSCO output directory, which, to be honest, doesn't have the most user-friendly structure. However, porting these changes to the nf-core module seems excessive in my opinion. Most of the time, only advanced users will look at this, who probably are somewhat familiar with BUSCO and its structure. For most users, the summary alone will be alright.

2025-04-11 12:59 UTC, jfy133 commented
@prototaxites is gonna review this one as he's more familiar with BUSCO :D

2025-04-14 10:10 UTC, prototaxites reviewed
Hi @dialvarezs, 

Have had a look over and this looks really good - just a few very minor comments/considerations. I'm going to run a local test and look at the outputs - once I've done that and it looks OK I'll approve.

Edit: one point I'm unclear on:
- If I want to use auto-lineage, can I do that entirely online without a path to a local copy of the full BUSCO db?

2025-04-14 10:10 UTC, prototaxites commented on conf/test_ancient_dna.config
> +    busco_db                             = "https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb12.2024-11-14.tar.gz"
Does this still work with odb10 lineages?

2025-04-14 10:10 UTC, prototaxites commented on conf/test_ancient_dna.config
> +    busco_db                             = "https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb12.2024-11-14.tar.gz"
(thinking about @jfy133's busco lineage catch PR)

2025-04-14 10:10 UTC, prototaxites commented on subworkflows/local/bin_qc.nf
> +        qc_summaries = BUSCO_BUSCO.out.batch_summary
Stylistic thing but should this be prefixed with `ch_`? Same with `busco_lineage`

2025-04-14 10:14 UTC, jfy133 commented on subworkflows/local/bin_qc.nf
> +        qc_summaries = BUSCO_BUSCO.out.batch_summary
Yes, please use `ch_` for channels :)

2025-04-14 10:27 UTC, prototaxites commented on conf/test_ancient_dna.config
> +    busco_db                             = "https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb12.2024-11-14.tar.gz"
This file doesn't exist any more. Latest version is

https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb12.2025-04-11.tar.gz

2025-04-14 10:28 UTC, prototaxites commented on conf/test_ancient_dna.config
> +    busco_db                             = "https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb12.2024-11-14.tar.gz"
It might be worth bundling a busco lineage if they're small enough to avoid the problem of file name changes?

2025-04-14 11:59 UTC, prototaxites commented
Changes to make:
- prefix channels with `ch_`
- Update BUSCO lineage file path as tests fail otherwise - consider moving this to the mag test data

## Tests

### Testing BUSCO

```
nextflow run dialvarezs/mag -r "dev-busco" -resume --outdir results_busco_full -profile singularity,test --skip_gtdbtk --skip_maxbin2 --skip_concoct --skip_clipping --skip_prokka --skip_metaeuk --skip_prodigal --busco_db https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb12.2025-04-11.tar.gz --busco_clean false
```

Works - BUSCO output present for the given DB and included in BUSCO summary TSV and bin summary TSV.

```
nextflow run dialvarezs/mag -r "dev-busco" -resume --outdir results_busco_full -profile singularity,test --skip_gtdbtk --skip_maxbin2 --skip_concoct --skip_clipping --skip_prokka --skip_metaeuk --skip_prodigal --busco_db /lustre/scratch123/tol/resources/busco/2025-04-12/ --busco_clean false
```

Works - BUSCO output present for the given DB and included in BUSCO summary TSV and bin summary TSV. Quick eyeball shows BUSCO ran in auto_lineage mode as expected.

### Testing CSVTK summarising for other tools

```
nextflow run dialvarezs/mag -r "dev-busco" -resume --outdir results_checkm2 -profile singularity,test --skip_gtdbtk --skip_maxbin2 --skip_concoct --skip_clipping --skip_prokka --skip_metaeuk --skip_prodigal binqc_tool checkm2 --busco_db false
```

Works - CheckM2 output present in summary TSVs.

```
nextflow run dialvarezs/mag -r "dev-busco" -resume --outdir results_checkm -profile singularity,test --skip_gtdbtk --skip_maxbin2 --skip_concoct --skip_clipping --skip_prokka --skip_metaeuk --skip_prodigal binqc_tool checkm --busco_db false
```

Works - CheckM output present in summary TSVs.

2025-04-14 11:59 UTC, prototaxites requested changes
(see above comment)

2025-04-14 12:00 UTC, prototaxites commented on conf/test_ancient_dna.config
> +    busco_db                             = "https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb12.2024-11-14.tar.gz"
Validated that this version of BUSCO works with both odb10 and odb12 lineages - so we can merge this and ignore @jfy133's PR

2025-04-14 13:50 UTC, dialvarezs commented on conf/test_ancient_dna.config
> +    busco_db                             = "https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb12.2024-11-14.tar.gz"
Current bacteria_odb12 is over 50MB, so I will leave bacteria_odb10 for tests instead.
[bacteria_odb10.2024-01-08.tar.gz](https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb10.2024-01-08.tar.gz)                   04-Mar-2025 01:01      6M
[bacteria_odb12.2025-04-11.tar.gz](https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb12.2025-04-11.tar.gz)                   11-Apr-2025 20:43     54M

2025-04-14 20:48 UTC, prototaxites approved these changes
LGTM!

2025-04-15 01:25 UTC, dialvarezs commented
> On this point, I had a nosey at the module code. If you provide a lineage name/"auto" to BUSCO and no download path, it should download the relevant lineages automatically. But we're requiring that the busco_db parameter is either a local directory or a downloaded lineage zip. So mag can't use BUSCO in auto lineage in "online" mode?

Regarding this point, it already does that. By default, `busco_db` is null and in that case BUSCO downloads the database instead of using the directory as db cache. If `busco_db` is not null, then the pipeline adds `--offline` to the BUSCO command. 

> So the alternative is to overhaul the inputs so that the default is to provide a lineage name (or auto, auto_prok) as the db, and not require a local db to be provided. Maybe we could split off a parallel "busco_local_db" or similar for lineage files/local databases, that when set also enable the --offline flag. But I think all that should be for a separate PR.

To me, it makes sense that the parameter is called `busco_db` to keep consistency with the rest of the parameters (basically every `*_db` refers to a file). However, I agree it could be a good idea to explicitly expose the lineage. Right now we have `busco_lineage_auto_prok`, and it might make more sense to have `busco_lineage` instead, which could accept a specific lineage name as well as `auto`, `auto_prok`, or `auto_euk`.

2025-04-15 06:38 UTC, jfy133 approved these changes
I think this look good to me now codewise :)!

I'm doing a brief test run to cross-check the docs, but otherwise I think this will look great!
 
We should however also address issue https://github.com/nf-core/mag/issues/775  in this PR - I'm going to see if I can push a little more docs to this branch before @dialvarezs wakes up so he can merge :)

2025-04-15 06:38 UTC, jfy133 commented on docs/output.md
> +[BUSCO](https://busco.ezlab.org/) is a tool used to assess the completeness of a genome assembly. It is run on all the genome bins and high quality contigs obtained by the applied binning and/or binn
```suggestion
[BUSCO](https://busco.ezlab.org/) is a tool used to assess the completeness of a genome assembly. It is run on all the genome bins and high quality contigs obtained by the applied binning and/or binning refinement methods (depending on the `--postbinning_input` parameter).
By default, BUSCO is run in automated lineage selection mode in which it first tries to select the domain and then a more specific lineage based on phylogenetic placement.
If available, result files for the selected lineage are placed in the output directory.
If a lineage dataset is specified already with `--busco_db`, only results for this specific lineage will be generated.
```

2025-04-15 06:38 UTC, jfy133 commented on subworkflows/local/bin_qc.nf
> +                BUSCO_UNTAR([[id: ch_busco_db.getSimpleName()], ch_busco_db])
No changes needed for this PR: Ok this tripped me up at first as I was like, you shouldn't do a `getSimpleName` on a channel but then I realised it isn't a channel just a file...

I think we should come up with new conventions how to prefix things like this...

Maybe

ch_: for channels
fl_: for files
val_: for variables (Strings, integers etc)

What do you guys think? Can bring it up in the rest of the community too if you think it's important

2025-04-15 06:38 UTC, jfy133 commented on subworkflows/local/gtdbtk.nf
> -                [row.'GenomeBin', completeness, contamination]
Does this not matter anymore because the columns are fixed now in the BUSCO tables?

2025-04-15 07:02 UTC, jfy133 requested changes
This is not working if I download a lineage tar.gz file and supply the directory to the pipeline.

We need to either update the docs or fix this.

2025-04-15 07:22 UTC, jfy133 commented
Also at the end of the busco.log there is this !?!?!?!!?

```
2025-04-15 07:12:37 INFO:busco.BuscoRunner      Visit this page https://gitlab.com/ezlab/busco#how-to-cite-busco to see how to cite BUSCO
2025-04-15 07:12:37 DEBUG:urllib3.connectionpool        Starting new HTTPS connection (1): busco-data.ezlab.org:443
2025-04-15 07:12:37 DEBUG:urllib3.connectionpool        Starting new HTTPS connection (1): busco-data.ezlab.org:443
2025-04-15 07:12:37 DEBUG:urllib3.connectionpool        https://busco-data.ezlab.org:443 "PUT /upload/rundata202504150712378987408.txt HTTP/1.1" 201 0
2025-04-15 07:12:37 DEBUG:urllib3.connectionpool        https://busco-data.ezlab.org:443 "PUT /upload/rundata202504150712378987408.txt HTTP/1.1" 201 0
2025-04-15 07:12:37 DEBUG:busco.run_BUSCO       File uploaded successfully.
```

But we definitely say offline in the command

```
2025-04-15 07:12:09 DEBUG:busco.run_BUSCO       Command line: /opt/conda/bin/busco --cpu 4 --in input_seqs --out test_minigut-bacteria_odb12-busco --mode genome --lineage_dataset bacteria_odb12 --download_path busco_db --offline
```

2025-04-15 07:34 UTC, jfy133 commented
> This is not working if I download a lineage tar.gz file and supply the uncompressed directory to the pipeline, based on the instructions in teh help text of `busco_db` (supplying the `.tar.gz` itself works)
> 
> We need to either update the docs to state we don't support directory input to `--busco_db` or fix this.

My _feeling_ is that BUSCO expects a structure of:

```
<something>
    lineages/
        <taxlevel>_odb<XX>
```

But then we expect the user to supply the `<taxlevel>_odb<XX>` to `--busco_db` so we can pick up the lineage name... i.e., the bottom part of the structure BUSCO expects

2025-04-15 08:34 UTC, jfy133 commented
OK I've just gone full in and fixing all the things above myself :sweat_smile:  expect a push in a bit

2025-04-15 10:45 UTC, jfy133 reviewed
@prototaxites @dialvarezs ok I _think_ I'm done, please could you test/check the new docs make sense?

2025-04-15 10:45 UTC, dialvarezs commented on subworkflows/local/gtdbtk.nf
> -                [row.'GenomeBin', completeness, contamination]
Exactly!

2025-04-15 10:48 UTC, prototaxites commented on nextflow_schema.json
> +                    "description": "Download URL, tar.gz archive local path, or local uncompressed directory for an *_odb10 or *_odb12 BUSCO lineage datasets. If ",
```suggestion
                    "description": "Download URL, tar.gz archive local path, or local uncompressed directory for an *_odb10 or *_odb12 BUSCO lineage datasets.",
```

2025-04-15 10:50 UTC, prototaxites commented on subworkflows/local/bin_qc.nf
> +                BUSCO_UNTAR([[id: ch_busco_db.getSimpleName()], ch_busco_db])
I like it also - but might be worth waiting to see how DSL3 is going to look as AFAIK it's getting types

2025-04-15 11:04 UTC, jfy133 commented
> Can you explain what the changes you've made are/what you need me to test?

Sorry yes, the main changes are that I have added a new parameter called `--busco_db_lineage`, and the required input structure has changed (or rather is now actually defined/documented)
The lineage is no longer auto-inferred. If you don't supply this we assume BUSCO will do it's own 'auto' lineage selection.

I guess ideally the tests would be:

- Test with no `--busco_db` specified
- Test with `--busco_db` URL input
- Test with `--busco_db` local `.tar.gz`
- Test with `--busco_db` local directory (i.e., user unpacked `.tar.gz` in the _correct_ structure)

And each of those with 

- `--busco_db_lineage` being specified, and without this being specified (so auto mode)

And also check misspecifying the lineage name

I guess that would be the most comprehensive suit of tests... but you can do what you feel suitable :)

2025-04-15 11:20 UTC, dialvarezs commented
To further address #775 I guess we should also clarify in the docs how to setup a BUSCO database for offline auto lineage usage. This is basically running the provided busco command for that: `busco --download <all/prokaryota>` before the pipeline.

2025-04-15 11:38 UTC, jfy133 commented
> To further address #775 I guess we should also clarify in the docs how to setup a BUSCO database for offline auto lineage usage. This is basically running the provided busco command for that: `busco --download <all/prokaryota>` before the pipeline (I'll do it now).

That would be awesome! I did sort of start hinting towards that in the parameters docs... but I think we need a dedicated section in `usage.md` indeed as the parameters help text is getting veyrf long now :smiling_face_with_tear:

2025-04-16 03:42 UTC, jfy133 reviewed
@dialvarezs The text looks great! I just clarified it a bit. I've also taken the opportunity to extend your new section with additional advice on some of the other more tricky databases.

As Jim is now on holiday, and assuming you still have time, if you can check my text below, and review my changes/replicate the tests I listed above to check everything is working as expected, then we can merge (as you have Jim's approval already) - note however I'm away from myself from tomorrow.

2025-04-16 03:42 UTC, jfy133 commented on docs/usage.md
> +BUSCO can download lineage datasets automatically as it needs them, but this process can be slow if the internet connection is unstable, and may lead to redundant downloads across different samples.
```suggestion
BUSCO can download lineage datasets automatically as it needs them, but this process can be slow if the internet connection is unstable, and may lead to redundant downloads across different samples.
To avoid this, you can provide a local copy of a BUSCO lineage dataset using the --busco_db parameter.
The local directory must follow a specific structure for BUSCO to recognize it.
```

2025-04-16 03:42 UTC, jfy133 commented on docs/usage.md
> +This command downloads the specified lineage into the <your_db> directory and creates the required directory structure. <lineage> can be any supported dataset, such as `alphaproteobacteria_odb12`. Yo
```suggestion
This command downloads the specified lineage into the `<your_db>/` directory and creates the required directory structure.
`<lineage>` can be any [supported dataset](https://busco-data.ezlab.org/v5/data/lineages/), such as `alphaproteobacteria_odb12`.
You can also specify `prokaryota` or `all` to download multiple lineages, which is necessary for automatic lineage selection in offline mode.
```

2025-04-16 03:42 UTC, jfy133 commented on docs/usage.md
> +Alternatively, you can manually download a lineage tarball from [https://busco-data.ezlab.org/v5/data/lineages/](https://busco-data.ezlab.org/v5/data/lineages/), extract it, and place it in the appro
```suggestion
Alternatively, you can manually download a lineage tarball from [https://busco-data.ezlab.org/v5/data/lineages/](https://busco-data.ezlab.org/v5/data/lineages/), extract it, and place it in the appropriate location: `<your_db>/lineages/<taxa>_odb<XX>`.
The lineage directory (e.g., bacteria_odb12) should contain files such as `datase.cfg` and a `hmms/` subdirectory at the top level.
Then, you must provide `--busco_db <your_db>/` to the pipeline.
```

2025-04-16 03:42 UTC, jfy133 commented on docs/usage.md
> +#### BUSCO
```suggestion
### Databases

nf-core/mag uses multiple tools that require additional databases.
The pipeline will download these databases for you if not supplied via a pipeline-level parameter.
However, we generally recommend you download these databases manually once, and place them in a long-term storage directory or cache from where you can re-use the databases across runs.
Here we provide specific additional information for some of the downloading databases which can be more tricky to prepare.

For any other database, or in doubt, please check the [parameters page](https://nf-co.re/mag/parameters).

#### BUSCO
```

2025-04-16 03:42 UTC, jfy133 commented on docs/usage.md
> +
```suggestion

### CAT

> [! WARNING]
> This database is very large at ~180 GB!
> This can take a long time, so we strongly recommend downloading and unzipping prior the pipeline run.

This database can be downloaded from the [CAT developers' website](https://tbb.bio.uu.nl/bastiaan/CAT_prepare/), which is based in the Netherlands (and could be slow for other regions of the world)

### GTDB


> [! WARNING]
> This database is very large at ~110 GB!
> This can take a long time, so we strongly recommend downloading and unzipping prior the pipeline run.

This database can be downloaded from the [GTDB developers' website](default: https://data.gtdb.ecogenomic.org/releases/release220/220.0/auxillary_files/gtdbtk_package/full_package/), which is based in Australia (and could be slow for other regions of the world).
The developers also offer a 'split' archive of 10GB files that can be downloaded more stably and subsequently can be manually combined after [here](https://data.gtdb.ecogenomic.org/releases/release220/220.0/auxillary_files/gtdbtk_package/split_package/).
More documentation can be seen [here](https://ecogenomics.github.io/GTDBTk/installing/index.html#gtdb-tk-reference-data).

```

2025-04-16 07:02 UTC, dialvarezs commented
@jfy133 it looks perfect for me, so I'll wait for the tests and get it merged. Thanks!

2025-04-16 07:26 UTC, dialvarezs commented
@jfy133 I was thinking on reproducibility mainly. If you want to run auto lineage on a dataset from a specific date you could not get reproducible results unless you add `--offline`, otherwise BUSCO could download new datasets and the results might not be exactly the same.

But yes, you're right that in this case I'm assuming that the user downloaded a full copy of the dataset.

2025-04-16 07:30 UTC, jfy133 commented
> @jfy133 I was thinking on reproducibility mainly. If you want to run auto lineage on a dataset from a specific date you could not get reproducible results unless you add `--offline`, otherwise BUSCO could download new datasets and the results might not be exactly the same.
> 
> But yes, you're right that in this case I'm assuming that the user downloaded a full copy of the dataset.

I think ti's better to be a little more permissive, but yes could document - if you rely on autoselection then risk breaking reproducibility - what do you think?

2025-04-16 07:38 UTC, prototaxites commented on docs/usage.md
> +
Get off your phone Jim, you’re on holiday, etc…

Should that read “database.cfg”, not “datase.cfg”?

2025-04-16 07:50 UTC, dialvarezs commented
@jfy133 I updated the reproducibility docs regarding BUSCO

2025-04-17 10:46 UTC, jfy133 approved these changes
I think this looks good to me (wow, this ended up being a lot bigger job than I thought :smiling_face_with_tear:  - well done @dialvarezs !)

Please leave a comment once you've run all the tests listed and the output looks good, and you can merge!

2025-04-17 10:46 UTC, jfy133 commented on CHANGELOG.md
> +- [#730](https://github.com/nf-core/mag/pull/730) - Added `--busco_db_lineage` to provide a lineage for BUSCO database and `--busco_force_offline` to force offline mode (added by @dialvarezs, @jfy133
```suggestion
- [#730](https://github.com/nf-core/mag/pull/730) - Added `--busco_db_lineage` to allow specifying a specific lineage for BUSCO database and `--busco_force_offline` to force offline mode (added by @dialvarezs, @jfy133).
```

2025-04-17 10:46 UTC, jfy133 commented on docs/usage.md
> +This database can be downloaded from the [CAT developers' website](https://tbb.bio.uu.nl/bastiaan/CAT_prepare/), which is based in the Netherlands (and could be slow for other regions of the world)
```suggestion
This database can be downloaded from the [CAT developers' website](https://tbb.bio.uu.nl/bastiaan/CAT_prepare/), which is based in the Netherlands (and could be slow for other regions of the world).
```

2025-04-17 10:46 UTC, jfy133 commented on docs/usage.md
> +The developers also offer a 'split' archive of 10GB files that can be downloaded more stably and subsequently can be manually combined after [here](https://data.gtdb.ecogenomic.org/releases/release22
```suggestion
The developers also offer a 'split' archive of 10GB files that can be downloaded more stably from  [here](https://data.gtdb.ecogenomic.org/releases/release220/220.0/auxillary_files/gtdbtk_package/split_package/) and subsequently (manually) combined after.
```

2025-04-17 10:46 UTC, jfy133 commented on docs/usage.md
> +If reproducibility is crucial, you can enable the parameter `--busco_force_offline`.
```suggestion
If you have supplied all available lineages within your `--busco_db`, but want BUSCO to auto-select the lineage, and are running in an offline context, you can enable the parameter `--busco_force_offline`, for maximum reproducibility.
```

2025-04-17 10:46 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "This will prevent BUSCO from trying to download lineage datasets from the internet, and instead use the local files specified in `--busco_db`, ensuring reproducibili
```suggestion
                    "help_text": "This will prevent BUSCO from trying to download lineage datasets from the internet, and instead use the local files specified in `--busco_db`, ensuring reproducibility. Ensure you have sufficient lineages in your `--busco_db` pre-downloaded and unpacked"
```

2025-04-17 20:13 UTC, dialvarezs commented
## Lineage selected
- [ ] No `--busco_db`
- [ ] `--busco_db` URL input
- [ ] `--busco_db` local .tar.gz
- [ ] `--busco_db` local directory

## Auto lineage
- [ ] No `--busco_db` 
- [ ] `--busco_db` URL input
- [ ] `--busco_db` local .tar.gz
- [ ] `--busco_db` local directory

2025-04-21 15:26 UTC, dialvarezs commented
I found a problem when providing a db (path/tarball/url) and using autolineage selection. BUSCO attempts to download the data into the working directory. This works fine for a single sample, but it naturally fails with multiple BUSCO instances running concurrently.

I've been considering solutions, and my best idea so far is to introduce a new parameter ("copy_db" or something like that) to the BUSCO module. If set to `true`, instead of directly using the provided database directory directly, a copy should be created using a `cp -rL` command (or maybe stageInMode could work too). In MAG, this `copy_db` parameter should be set to true in situations where BUSCO is expected to download data (basically auto lineage enabled without force-offline).

What do you think about this @jfy133?

2025-04-24 13:25 UTC, jfy133 commented
> I found an issue when providing a db (path/tarball/url) and using autolineage selection. BUSCO attempts to download the data into the provided directory, and this works fine for a single sample, but it naturally fails with multiple BUSCO instances running concurrently.
> 
> I've been considering solutions, and my best idea so far is to introduce a new parameter ("copy_db" or something like that) to the BUSCO module. If set to `true`, instead of directly using the provided database directory, a copy should be created using a `cp -rL` command. In mag, this `copy_db` parameter should be set to true in situations where BUSCO is expected to download data (basically db provided + auto lineage enabled + no force-offline).
> 
> What do you think about this @jfy133?

By providing a DB you mean it that doesn't have all of the lineages already downloaded? But conceptually I see the issue. 

However the proposed solution sounds dangerous to me as you could have 1000s of BUSCO runs and copying every time will be really bad on both IO and HDD space.

Maybe we should then instead go we have to go back to the stricter method of you can only use autolineage selection if you don't specify a database? But this would suck for offline clusters...

We might be trapped between a rock and a hardplace here... 

@prototaxites any thoughts?

2025-04-24 14:10 UTC, prototaxites commented
I don't like the idea of adding more parameters to the pipeline for what is currently the default option for bin QC - this should really provide a simple plug-and-play option that works easily for most users.

IMO if you provide a local (or URL) BUSCO db, BUSCO should never connect to the internet - we should just enforce `--offline` - which as I understand the problem would elide this issue? I think we can just add an explanatory note that if you want to use auto-lineage selection with a local copy of the DB, it's on the user to check that the local copy is complete and up-to-date.

2025-04-24 15:39 UTC, jfy133 commented
> > I don't like the idea of adding more parameters to the pipeline for what is currently the default option for bin QC - this should really provide a simple plug-and-play option that works easily for most users.
> > 
> > IMO if you provide a local (or URL) BUSCO db, BUSCO should never connect to the internet - we should just enforce `--offline` - which as I understand the problem would elide this issue? I think we can just add an explanatory note that if you want to use auto-lineage selection with a local copy of the DB, it's on the user to check that the local copy is complete and up-to-date.
> 
> That sounds good to me (in retrospect), sorry for complicating it before @dialvarezs ! (Iirc that's what you had before...)

2025-04-24 20:01 UTC, dialvarezs commented
Don't worry @jfy133, I was not 100% sure also, but as I was implementing it, it seemed to be getting overly complicated. So keeping it as it was before seems the most optimal solution for me also.

So, I reverted all those commits, but keeping the usage docs changes and improving the BUSCO section a bit.

2025-04-25 08:39 UTC, prototaxites reviewed
Couple of questions:

1. Do we need the parameter `busco_auto_lineage_prok` any more? Can we set this up so that the default `busco_lineage` param is `auto` by default, but can be set to `auto_prok`, `auto_euk` or a specific lineage?
2. What's the status with the `--busco_force_offline` param now?
3. It looks like the docs seem to say that running in auto mode requires an internet connection:

> By default, BUSCO runs in offline mode only when both a local database path is provided via `--busco_db` and a specific lineage is set with `--busco_db_lineage`. 

But we can set "auto" for the lineage, which is not a "specific" lineage?

2025-04-25 08:39 UTC, prototaxites commented on docs/usage.md
> +If you have supplied all available lineages within your `--busco_db`, but want BUSCO to auto-select the lineage, and are running in an offline context, you can enable the parameter `--busco_force_off
Is this still relevant?

2025-04-25 13:34 UTC, dialvarezs commented
> Do we need the parameter busco_auto_lineage_prok any more? Can we set this up so that the default busco_lineage param is auto by default, but can be set to auto_prok, auto_euk or a specific lineage?

Agree 100%. It' a bit redundant if we consider that `busco_lineage` supports `auto/auto_prok`.

> What's the status with the --busco_force_offline param now?

It doesn't exist anymore.

> It looks like the docs seem to say that running in auto mode requires an internet connection:

Good catch, I missed that one.

> But we can set "auto" for the lineage, which is not a "specific" lineage?

Yes, you're right. We are not filtering out that option, only it was not documented. And if we remove `busco_auto_lineage_prok` it would make more sense.

2025-04-25 13:35 UTC, dialvarezs commented
@jfy133 any thoughts regarding the removal of `busco_auto_lineage_prok`?

2025-04-25 13:51 UTC, prototaxites commented on docs/usage.md
> +If you have supplied all available lineages within your `--busco_db`, but want BUSCO to auto-select the lineage, and are running in an offline context, you can enable the parameter `--busco_force_off
^

2025-04-28 07:46 UTC, jfy133 reviewed
Yes, fine to me to remove the auto prok, thingy!

2025-04-28 07:46 UTC, jfy133 commented on conf/modules.config
> -    withName: 'BUSCO_SUMMARY|QUAST_BINS|QUAST_BINS_SUMMARY' {
**question:** Just to check, the two QUAST settings are covered elsewhere, is that correct? 

I vaguely remember eitherthinking or asking before, but I've forgotten the answer :sweat_smile:

2025-04-28 07:46 UTC, jfy133 commented on docs/usage.md
> +Alternatively, you can manually download a lineage tarball from [https://busco-data.ezlab.org/v5/data/lineages/](https://busco-data.ezlab.org/v5/data/lineages/), extract it, and place it in the appro
**suggestion:** 
```suggestion
Alternatively, you can manually download a specific lineage tarball from [https://busco-data.ezlab.org/v5/data/lineages/](https://busco-data.ezlab.org/v5/data/lineages/), extract it, and place it in the appropriate location: `<your_db>/lineages/<taxa>_odb<XX>`.
```

2025-04-28 07:46 UTC, jfy133 commented on docs/usage.md
> +If you have supplied all available lineages within your `--busco_db`, but want BUSCO to auto-select the lineage, and are running in an offline context, you can enable the parameter `--busco_force_off
**suggestion:** 
```suggestion
```

2025-04-28 07:46 UTC, jfy133 commented on nextflow.config
>      busco_auto_lineage_prok              = false
**praise:** 
```suggestion
```

2025-04-28 07:46 UTC, jfy133 commented on docs/usage.md
> +Using auto lineage mode with BUSCO may lead to non-reproducible results, since the databases are frequently updated and automatic lineage selection depends on the version of the database used when ru
**suggestion:** 
```suggestion
Using auto lineage mode with BUSCO may lead to non-reproducible results, since the databases are frequently updated and automatic lineage selection depends on the version of the database used when running BUSCO.
Therefore we strongly recommend downloading the lineages in advance and specifying the lineage to check against.
You can also download `all` lineages (see [Databases](#databases), and specify this in `--busco_db_lineages` to check against all lineages, if you're not sure which lineage to select.
```

I think?

2025-04-28 07:46 UTC, jfy133 commented on nextflow.config
> +    busco_db_lineage                     = null
**question:** should this be set to `auto` then? Or is no selection behaviour `auto`?

2025-04-29 06:49 UTC, jfy133 commented
Code look good @dialvarezs ! 

Just need a re-pass through the tests to make sure every combination of `--busco_db = ( no_db | db ) * --busco_db_lineage = (auto | all | specific lineage)` works correctly (basically the tests you had in our table above)

If they all pass I think we can merge (finally!)

2025-04-29 11:00 UTC, dialvarezs commented
## Lineage selected
- [ ] No `--busco_db`
- [ ] `--busco_db` URL input
- [ ] `--busco_db` local .tar.gz
- [ ] `--busco_db` local directory with proper structure

## Auto lineage
- [ ] No `--busco_db`
- [ ] `--busco_db` local directory with full dataset

2025-04-29 11:58 UTC, dialvarezs commented
All tests passed @jfy133!

2025-04-29 12:00 UTC, prototaxites approved these changes
A few minor documentation comments.

2025-04-29 12:00 UTC, prototaxites commented on nextflow_schema.json
> +                    "description": "Download URL, tar.gz archive local path, or local uncompressed directory for an *_odb10 or *_odb12 BUSCO lineage datasets.",
```suggestion
                    "description": "Download URL, local tar.gz archive, or local uncompressed directory for an *_odb10 or *_odb12 BUSCO lineage dataset.",
```

2025-04-29 12:00 UTC, prototaxites commented on nextflow_schema.json
> +                    "description": "Name of the BUSCO *_odb10 or *_odb12 lineage to check against. Additionally supports 'auto' and 'auto_prok' for automatic lineage selection mode.",
```suggestion
                    "description": "Name of the BUSCO *_odb10 or *_odb12 lineage to check against. Additionally supports 'auto', 'auto_prok', and 'auto_euk' for automatic lineage selection mode.",
```

Since we have Eukaryote-specific stuff in the pipeline

2025-04-29 12:00 UTC, prototaxites commented on subworkflows/local/utils_nfcore_mag_pipeline/main.nf
> +        log.warn('[nf-core/mag]: WARNING: You have supplied a --busco_db directory, but not specified a lineage with `--busco_db_lineage` - this may cause BUSCO to attempt to auto-download files for
If `--busco_db` is provided, we are now forcing offline - so this isn't the case any more?

Can we make it so that `--busco_db_lineage` is a required param with default 'auto'? Then have:

```suggestion
        log.warn('[nf-core/mag]: WARNING: You have supplied a database to --busco_db - BUSCO will run in offline mode. Please note that BUSCO may fail if you have an incomplete database and are running with --busco_db_lineage auto!')
```

2025-04-29 12:00 UTC, prototaxites commented on subworkflows/local/utils_nfcore_mag_pipeline/main.nf
> +    if (!params.skip_binqc && params.binqc_tool == 'busco') {
Can we wrap all these try-catches in this block for conciseness?

2025-04-29 12:28 UTC, jfy133 commented
I've rolled back the nf-schema version as per https://nfcore.slack.com/archives/C04QR0T3G3H/p1745504826926699

To hopefully let all our edge releases work

2025-04-29 12:28 UTC, jfy133 commented on nextflow.config
> +    id 'nf-schema@2.2.0'
**suggestion:** 
```suggestion
    id 'nf-schema@2.2.1'
```

Use recommended version as per https://nfcore.slack.com/archives/C04QR0T3G3H/p1745504826926699

2025-04-29 12:29 UTC, jfy133 approved these changes
@dialvarezs once Jim's final comment is addressed, you have an OK to merge !

2025-05-09 08:56 UTC, prototaxites approved these changes

2025-05-09 09:30 UTC, jfy133 commented
@dialvarezs GO GO GO

2025-05-09 09:31 UTC, merged